@startuml Обработка изображения
!theme cerulean
start
:Получение RTSP-потока;
while (Включена обработка изображения?) is (Да)
  :Декодирование видеокадра;
  :Передача кадра в OCR;
  if (Обнаружен объект?) then (Да)
    :Вычисление смещения объекта;
    :Отправка команды PTZ-контроллеру;
    :Камера корректирует позицию;
  else (Нет)
    :Продолжение анализа;
  endif
  :Обновление потока;
endwhile
:Завершение работы;
stop
@enduml